### ISSUE TITLE
Grammar on index.html

### ISSUE THREAD

**Issue by TheGamerKing777** [helloyanis/helloyanis.github.io#1]
Hello there!
Just were curious to see what other things you have been into.
While reading some of the files and previewing the website, I saw a small grammar that you can fix.

In Line 95: "Coming soom..."
Now you know ;)

Perhaps also changing the year in Line 101, if you plan to launch it soon.

Anyway, good luck!
Hope I helped you :)

**Comment by helloyanis** [comment]
Fixed, thanks!
